services:
  # See https://render.com/docs/blueprint-spec for more info on render blueprints
  - type: web
    name: renderdashapp
    env: python
    plan: free
    # A requirements.txt file must exist
    buildCommand: pip install -r requirements.txt
    # A src/app.py file must exist and contain `server=app.server`
    startCommand: gunicorn --chdir src flask_app:server
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
